options:
  control-network:
    type: string
    description: |
      Network where API services are listening on.
      The IP address and netmask of the control network (e.g. 192.168.0.0/24) or physical device name.
      This network will be used for all services in the charm.
      In Contrail this network is called as API(/MGMT) network.
      If not specified, default network will be used.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  docker_runtime:
    type: string
    default: upstream
    description: |
      Docker runtime to install valid values are "upstream" (Docker PPA), "apt" (Ubuntu archive),
      "auto" (Ubuntu archive), or "custom" (must have set `docker_runtime_repo` URL,
      `docker_runtime_key_url` URL and `docker_runtime_package` name).
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_key_url:
    type: string
    description: |
      Custom Docker repository validation key URL.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_package:
    type: string
    description: |
      Custom Docker repository package name.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_repo:
    type: string
    description: |
      Custom Docker repository, given in deb format. Use `{ARCH}` to determine architecture at runtime.
      Use `{CODE}` to set release codename.
      E.g. `deb [arch={ARCH}] https://download.docker.com/linux/ubuntu {CODE} stable`.
      Warning! The changes will not be applied after the package is installed.
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  docker-log-driver:
    type: string
    default: json-file
    description: |
      A logging driver for the serviceâ€™s containers.
  docker-log-options:
    type: string
    default: "max-size=20m max-file=5"
    description: |
      Logging options for the logging driver. Logging options available depend
      on which logging driver you use.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
  http_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  https_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  no_proxy:
    type: string
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long
  haproxy-http-mode:
    type: string
    default: http
    description: |
      Mode for haproxy for http backends - http or https.
      https means that haproxy will be configured with SSL termination.
      http configures haproxy without SSL and http services (config-api and
      analytics-api) can be accessed via haproxy by http connection.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup