options:
  api-network:
    type: string
    description: |
      The IP address and netmask of the API network (e.g. 192.168.0.0/24).
      This network will be used for Contrail endpoints.
      If not specified, default network will be used.
  control-network:
    type: string
    description: |
      The IP address and netmask of the control network (e.g. 10.0.0.0/24).
      This network will be used by vrouter agents for XMPP connections.
      If not specified, API or default network will be used.
  auth-mode:
    type: string
    default: rbac
    description: |
      It represents 'aaa_mode' configuration key of Contrail.
      Can be one of: 'rbac', 'cloud-admin' or 'no-auth'
      Authentication mode. Detailed information can be found in the Contrail documentation.
      https://github.com/Juniper/contrail-controller/wiki/RBAC
      In case of 'rbac' charm will configure Contrail to RBAC mode and administrator must
      configure RBAC rules to allow users to work.
      In case of 'cloud-admin' charm will configure Contrail in compatible mode.
  cloud-admin-role:
    type: string
    default: admin
    description: |
      Role name in keystone for users that have full access to everything.
  global-read-only-role:
    type: string
    description: |
      Role name in keystone for users that have read-only access to everything.
  vip:
    type: string
    description: |
      Contrail API VIP to be used for configuring client-side software like neutron plugin.
      (to be set up also in KeepAlived charm configuration if itâ€™s used for HA)
      Private IP of the first Contrail API unit will be used if not set.
  use-external-rabbitmq:
    type: boolean
    default: false
    description: |
      Charm will wait for external AMQP relation if set.
      Charm will use internal RabbitMQ server if not set.

      NOTE: Changing this flag after deployment is dangerous!
  cassandra-minimum-diskgb:
    type: string
    default: "20"
    description: |
      Contrail has this as parameter and checks it at startup.
      If disk is smaller then status of DB is not good.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  flow-export-rate:
    type: string
    default: "0"
    description: |
      Defines how much flow records will be exported by vRouter agent
      to the Contrail Collector when a flow is created or deleted.
  docker-registry:
    type: string
    description: |
      URL of docker-registry. Should be passed only if registry is not secured and must be added to docker config to allow work with it.
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  image-name:
    type: string
    description: |
      Full docker's image name.
  image-tag:
    type: string
    description: |
      Tag of docker image.
