options:
  control-network:
    type: string
    description: |
      The IP address and netmask of the control network (e.g. 192.168.0.0/24).
      This network will be used for Contrail endpoints.
      If not specified, default network will be used.
  auth-mode:
    type: string
    default: rbac
    description: |
      It represents 'aaa_mode' configuration key of Contrail.
      Can be one of: 'rbac', 'cloud-admin' or 'no-auth'
      Authentication mode. Detailed information can be found in the Contrail documentation.
      https://github.com/Juniper/contrail-controller/wiki/RBAC
      In case of 'rbac' charm will configure Contrail to RBAC mode and administrator must
      configure RBAC rules to allow users to work.
      In case of 'cloud-admin' charm will configure Contrail in compatible mode.
  cloud-admin-role:
    type: string
    default: admin
    description: |
      Role name in keystone for users that have full access to everything.
  global-read-only-role:
    type: string
    description: |
      Role name in keystone for users that have read-only access to everything.
  vip:
    type: string
    description: |
      Contrail API VIP to be used for configuring haproxy relation for external clients.
      To be set up also in KeepAlived charm configuration if itâ€™s used for HA.
      All internal clients like vrouter-agent and openstack clients like neutron
      will be configured with list of unit's IP-s.
  cassandra-minimum-diskgb:
    type: string
    default: "20"
    description: |
      Contrail has this as parameter and checks it at startup.
      If disk is smaller then status of DB is not good.
  cassandra-jvm-extra-opts:
    type: string
    description: |
      Memory limits for Java process of Cassandra.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  flow-export-rate:
    type: string
    default: "0"
    description: |
      Defines how much flow records will be exported by vRouter agent
      to the Contrail Collector when a flow is created or deleted.
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
  http_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  https_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  no_proxy:
    type: string
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long
  local-rabbitmq-hostname-resolution:
    type: boolean
    default: false
    description: |
      Write RabbitMQ resolutions for cluster node names into /etc/hosts based
      on addresses from subnets configured in control-network config
      as well as a system hostname plus '-contrail-rmq' postfix. This config
      option is useful for multi-homed setups where a system hostname in the
      configured DNS does not correspond to an address used for RabbitMQ
      clustering traffic.
