options:
  install-sources:
    type: string
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  physical-interface:
    type: string
    description: |
      Specify the interface to install vhost0 on. If left empty, vhost0 will
      be installed on the default gateway interface.
  vhost-gateway:
    type: string
    default: auto
    description: |
      Specify the gateway for vhost0, either an IPv4 address or keyword 'auto'.
      'auto' will set gateway automatically based on host's existing routes.
  remove-juju-bridge:
    type: boolean
    default: true
    description: |
      Juju on MAAS creates bridges for deploying LXD/LXC and KVM workloads.
      Enable this to remove such a bridge if you want to install vhost0 directly
      on the underlying interface.
  dpdk:
    type: boolean
    default: false
    description: Use user space DPDK vRouter
  dpdk-driver:
    type: string
    default: uio_pci_generic
    description: |
      DPDK driver to use for physical interface.
      Interface can be specified using vhost-interface.
  dpdk-hugepages:
    type: string
    default: 70%
    description: |
      Number of huge pages to reserve for use with DPDK vRouter and OpenStack
      instances.
      Value can be specified as percentage of system memory e.g. 70% or as
      number of huge pages e.g. 1434.
  dpdk-coremask:
    type: string
    default: "1"
    description: |
      vRouter CPU affinity mask. Determines on which CPUs DPDK vRouter will run.
      Value can be specified as either a hexidecimal bitmask e.g. 0xF or
      as a numbered list separated by commas e.g. 0,1 (ranges are also supported
      using '-' e.g. 0-2).
      It must specify only real cores cause contrail-vrouter-dpdk service will
      fail if specified core number is not present in the system.
  dpdk-main-mempool-size:
    type: string
    description: |
      Main packet pool size.
  dpdk-pmd-txd-size:
    type: string
    description: |
      DPDK PMD Tx Descriptor size.
  dpdk-pmd-rxd-size:
    type: string
    description: |
      DPDK PMD Rx Descriptor size.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
