options:
  physical-interface:
    type: string
    description: |
      Specify the interface to install vhost0 on. If left empty, vhost0 will
      be installed on the default gateway interface.
  vhost-gateway:
    type: string
    default: auto
    description: |
      Specify the gateway for vhost0, either an IPv4 address or keyword 'auto'.
      'auto' will set gateway automatically.
  dpdk:
    type: boolean
    default: false
    description: Use user space DPDK vRouter
  dpdk-driver:
    type: string
    default: uio_pci_generic
    description: |
      DPDK driver to use for physical interface.
      Interface can be specified using vhost-interface.
  dpdk-hugepages:
    type: string
    default: 70%
    description: |
      Number of huge pages to reserve for use with DPDK vRouter and OpenStack
      instances.
      Value can be specified as percentage of system memory e.g. 70% or as
      number of huge pages e.g. 1434.
  dpdk-coremask:
    type: string
    default: "1"
    description: |
      vRouter CPU affinity mask. Determines on which CPUs DPDK vRouter will run.
      Value can be specified as either a hexidecimal bitmask e.g. 0xF or
      as a numbered list separated by commas e.g. 0,1 (ranges are also supported
      using '-' e.g. 0-2).
      It must specify only real cores cause contrail-vrouter-dpdk service will
      fail if specified core number is not present in the system.
  dpdk-main-mempool-size:
    type: string
    description: |
      Main packet pool size.
  dpdk-pmd-txd-size:
    type: string
    description: |
      DPDK PMD Tx Descriptor size.
  dpdk-pmd-rxd-size:
    type: string
    description: |
      DPDK PMD Rx Descriptor size.
  sriov-physical-interface:
    type: string
    description: |
      Interface name for SR-IOV. This parameter and sriov-numvfs will be passed
      into agent container that will configure SR-IOV.
  sriov-numvfs:
    type: string
    description: |
      NumVFS for specified device. This parameter and sriov-physical-interface
      will be passed into agent container that will configure SR-IOV.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  docker_runtime:
    type: string
    default: upstream
    description: |
      Docker runtime to install valid values are "upstream" (Docker PPA), "apt" (Ubuntu archive),
      "auto" (Ubuntu archive), or "custom" (must have set `docker_runtime_repo` URL,
      `docker_runtime_key_url` URL and `docker_runtime_package` name).
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_key_url:
    type: string
    description: |
      Custom Docker repository validation key URL.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_package:
    type: string
    description: |
      Custom Docker repository package name.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_repo:
    type: string
    description: |
      Custom Docker repository, given in deb format. Use `{ARCH}` to determine architecture at runtime.
      Use `{CODE}` to set release codename.
      E.g. `deb [arch={ARCH}] https://download.docker.com/linux/ubuntu {CODE} stable`.
      Warning! The changes will not be applied after the package is installed.
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  docker-log-driver:
    type: string
    default: json-file
    description: |
      A logging driver for the serviceâ€™s containers.
  docker-log-options:
    type: string
    default: "max-size=20m max-file=5"
    description: |
      Logging options for the logging driver. Logging options available depend
      on which logging driver you use.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
  http_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  https_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  no_proxy:
    type: string
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long
  wait-for-external-plugin:
    type: boolean
    default: false
    descripton: |
      Enable external vRouter datapath plugin. This can be used with the agilio-vrouter
      charm to enable a hardware offloaded vRouter datapath.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
