version: '2'
volumes:
 config_cassandra:
 config_zookeeper:
services:
  node-init:
    image: "{{ container_registry }}/contrail-node-init:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - CONTRAIL_STATUS_IMAGE="{{ container_registry }}/contrail-status:{{ contrail_version_tag }}"
    privileged: true
    pid: host
    network_mode: "host"
    volumes:
      - /usr/bin:/host/usr/bin
      - /etc/contrail/ssl/{{ module }}:/etc/contrail/ssl
      - /etc/sysctl.d:/etc/sysctl.d
      - /etc/hosts:/etc/hosts
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
{{ logging | indent(4,True) }}
  nodemgr:
    image: "{{ container_registry }}/contrail-nodemgr:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - NODE_TYPE=config-database
      - CASSANDRA_CQL_PORT=9041
      - CASSANDRA_JMX_LOCAL_PORT=7201
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - node-init
    depends_on:
      - node-init
    restart: always
{{ logging | indent(4,True) }}
  cassandra:
    image: "{{ container_registry }}/contrail-external-cassandra:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - CASSANDRA_SEEDS={{ controller_servers|sort|join(',') }}
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=contrail_database
      - CASSANDRA_PORT=9161
      - CASSANDRA_CQL_PORT=9041
      - CASSANDRA_SSL_STORAGE_PORT=7013
      - CASSANDRA_STORAGE_PORT=7012
      - CASSANDRA_JMX_LOCAL_PORT=7201
      - NODE_TYPE=config-database
    volumes:
      - config_cassandra:/var/lib/cassandra/data
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
  zookeeper:
    image: "{{ container_registry }}/contrail-external-zookeeper:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - ZOOKEEPER_NODES={{ controller_servers|sort|join(',') }}
      - ZOOKEEPER_PORTS=2888:3888
      - ZOOKEEPER_PORT=2181
      - NODE_TYPE=config-database
    volumes:
      - config_zookeeper:/data
      - config_zookeeper:/datalog
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
  rabbitmq:
    image: "{{ container_registry }}/contrail-external-rabbitmq:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - RABBITMQ_NODES={{ controller_servers|sort|join(',') }}
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - NODE_TYPE=config-database
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
